/**
 * VOUCH Firestore Schema
 *
 * This file documents the Firestore collections and their structure.
 * Use this as reference when writing/reading from Firebase.
 */

import { Timestamp } from 'firebase/firestore';

// ============================================================================
// COLLECTIONS
// ============================================================================

/**
 * Collection: users
 * Document ID: Privy user ID (same across web and mobile)
 */
export interface User {
  privyId: string;
  walletAddress?: string;
  displayName?: string;
  email?: string;
  createdAt: Timestamp;
  stats: {
    totalVouches: number;
    verifiedVouches: number;
    credibilityScore: number; // 0-100, based on biometric verification rate
  };
}

/**
 * Collection: vouches
 * Document ID: Auto-generated by Firestore
 */
export interface Vouch {
  userId: string; // Privy user ID
  workoutData: {
    type: 'running' | 'cycling' | 'strength' | 'yoga' | 'swimming' | 'other';
    duration: number; // minutes
    calories: number;
    distance?: number; // meters (for running, cycling)
    heartRate?: number; // average BPM
    verified: boolean; // true if from HealthKit/Google Fit, false if manual
    source: 'healthkit' | 'googlefit' | 'manual' | 'web';
  };
  photoUrl?: string; // Firebase Storage URL
  platform: 'web' | 'mobile';
  timestamp: Timestamp;
}

/**
 * Collection: squads
 * Document ID: Auto-generated by Firestore
 */
export interface Squad {
  name: string;
  members: string[]; // Array of Privy user IDs
  createdAt: Timestamp;
  settings: {
    roastLevel: 'brutal' | 'harsh' | 'savage';
    minVouchesPerWeek: number; // Default: 5
    requireBiometric: boolean; // If true, manual entries trigger roasts
  };
}

/**
 * Collection: roasts
 * Document ID: Auto-generated by Firestore
 */
export interface Roast {
  userId: string; // Target of roast (Privy user ID)
  squadId: string; // Squad where roast was triggered
  message: string; // AI-generated roast message
  reason: 'missed_vouch' | 'manual_entry' | 'streak_broken' | 'inactive';
  timestamp: Timestamp;
  severity: 'brutal' | 'harsh' | 'savage';
}

// ============================================================================
// STORAGE PATHS
// ============================================================================

/**
 * Firebase Storage paths
 */
export const STORAGE_PATHS = {
  /**
   * Workout proof photos
   * Path: /vouches/{userId}/{timestamp}.jpg
   */
  vouchPhoto: (userId: string, timestamp: number) =>
    `vouches/${userId}/${timestamp}.jpg`,

  /**
   * User avatar photos
   * Path: /avatars/{userId}.jpg
   */
  avatar: (userId: string) =>
    `avatars/${userId}.jpg`,
} as const;

// ============================================================================
// FIRESTORE COLLECTION PATHS
// ============================================================================

export const COLLECTIONS = {
  USERS: 'users',
  VOUCHES: 'vouches',
  SQUADS: 'squads',
  ROASTS: 'roasts',
} as const;

// ============================================================================
// EXAMPLE USAGE
// ============================================================================

/**
 * Example: Creating a new vouch
 *
 * ```typescript
 * import { collection, addDoc, Timestamp } from 'firebase/firestore';
 * import { db } from '@/services/firebase';
 * import { COLLECTIONS, Vouch } from '@/firebase/firestore-schema';
 *
 * const newVouch: Vouch = {
 *   userId: user.id,
 *   workoutData: {
 *     type: 'running',
 *     duration: 30,
 *     calories: 250,
 *     distance: 5000,
 *     heartRate: 145,
 *     verified: true,
 *     source: 'healthkit',
 *   },
 *   photoUrl: 'https://storage.googleapis.com/...',
 *   platform: 'mobile',
 *   timestamp: Timestamp.now(),
 * };
 *
 * await addDoc(collection(db, COLLECTIONS.VOUCHES), newVouch);
 * ```
 */

/**
 * Example: Reading user data
 *
 * ```typescript
 * import { doc, getDoc } from 'firebase/firestore';
 * import { db } from '@/services/firebase';
 * import { COLLECTIONS, User } from '@/firebase/firestore-schema';
 *
 * const userDoc = await getDoc(doc(db, COLLECTIONS.USERS, privyUserId));
 * const userData = userDoc.data() as User;
 * ```
 */
